name: Run Tests and Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: make coverage | tee test_results.txt

      - name: Post test results as PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: test_results.txt
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build the application
        run: go build -o obd2-tui ./cmd

      - name: Upload binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: obd2-tui-binary
          path: ./obd2-tui
